language: java

jdk:
  - oraclejdk8

script: mvn package checkstyle:check

before_script:
  - mvn clean

before_install:
  - mvn install

after_success:
  - mvn clean test jacoco:report coveralls:report